<a href="https://colab.research.google.com/github/amathe1/Neural_Networks/blob/main/House_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem statement : Predicting the house price based on area & no of bed rooms

In [1]:
#Step1 - importing libraries
import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
#Step2 - create dataset
# [800, 2] - 800 square ft of house with 2 bedrooms with price $200
x = torch.tensor([
    [800, 2],
    [1000, 3],
    [1200, 3],
    [1500, 4],
    [1800, 4]
], dtype=torch.float32)

y = torch.tensor([[200],[260],[300],[360],[420]], dtype=torch.float32)

In [4]:
x

tensor([[ 800.,    2.],
        [1000.,    3.],
        [1200.,    3.],
        [1500.,    4.],
        [1800.,    4.]])

In [5]:
y

tensor([[200.],
        [260.],
        [300.],
        [360.],
        [420.]])

In [6]:
#Step3 - Normalize the input (important for neural networks)
# Ideally we can use min-max/z-scalar normalization techniques but as it this is for learning purpose, we are using a generalized way.
"""
If you observe carefully, data is not in uniform state.
Consider elements in the first variable [800, 2], there is a huge difference between 800 & 2.
Hence we need to normalize the data. We are using a generalized normalization by dividing each number with the large number in that tensor.

Observe that, we have mentioned dim = 0 means, it will consider the column values.
                         but if dim = 1 then, it will consider the row values.
"""
x = x / x.max(dim=0).values
y = y / y.max()

In [7]:
x

tensor([[0.4444, 0.5000],
        [0.5556, 0.7500],
        [0.6667, 0.7500],
        [0.8333, 1.0000],
        [1.0000, 1.0000]])

In [8]:
y

tensor([[0.4762],
        [0.6190],
        [0.7143],
        [0.8571],
        [1.0000]])

Please observe that all the input values are normalized now.

In [9]:
#Step4 - Define model
"""
1) Sequential is a container in NN, which will have Linear & Activation functions
2) All the methods inside Sequential container will execute in a sequence one after another

Why we are not applying any activation function to output layer for regression problem ?
-  nn.Linear already performs a linear transformation
-  Mathematically : y=Wx+b
-  That itself is a linear activation function.
-  If you don’t apply anything after it, the output remains: f(x)=Wx+b
-  Which is exactly what we want for regression.

Why Linear for Regression?

Regression targets:
House prices
Temperature
Salary
Stock value

These values:
Can be large
Can be any real number
Should not be restricted

If you used:
Sigmoid → output between 0 and 1 ❌
ReLU → cannot predict negative values ❌
Tanh → output between -1 and 1 ❌

So we leave it linear.
"""

model = nn.Sequential(
    nn.Linear(2, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)

In [10]:
#Step5 - Loss & Optimizer

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [12]:
#Step6 - Training Loop

for epoc in range(500): # run model 50 iterations
  pred = model(x)       # get predicted value by passing input values 'x' to our model
  loss = criterion(pred, y)  # calculate loss once we have predicted value from above step

  optimizer.zero_grad() # set gradient to '0', otherwise gradient values will accumulate
  loss.backward()       # initialize backward propagation
  optimizer.step()      # adjust weights & biases (W_new = W_old - (learning rate)*(dL/dW_old), B_new = B_old - (learning rate)*(dL/dB_old))

  if epoc % 50 == 0: # intentionally printing only random epocs
    print(f"Epoch {epoc}, Loss {loss.item():.4f}") # converting pytorch tensor values into float values using item()



Epoch 0, Loss 0.0027
Epoch 50, Loss 0.0023
Epoch 100, Loss 0.0019
Epoch 150, Loss 0.0016
Epoch 200, Loss 0.0013
Epoch 250, Loss 0.0011
Epoch 300, Loss 0.0009
Epoch 350, Loss 0.0007
Epoch 400, Loss 0.0005
Epoch 450, Loss 0.0004


In [13]:
#Step7 - Test Prediction

test = torch.tensor([1600, 4], dtype=torch.float32) # Creating test data
test = test / x.max(dim=0).values # Normalizing test data

print("Predicted price : ", model(test) * 420) # Remember that, for price (y), we divided each value with max value in the tensor, which is 420
                                               # Hence we are multiplying that value to final test result to get the actual predicted proce of house

Predicted price :  tensor([502851.4062], grad_fn=<MulBackward0>)
